### ISSUE TITLE
 Run specific spec file

### ISSUE THREAD

**Issue by mjlucero** [migalons/angular-wdio6-builder-demo#2]
Hello! Thanks for the great demo, I have a quick question about how we can run a specific spec file.

**Comment by migalons** [comment]
Hi.

In the configuration file, you specify what files to run (See e2e/wdio.config.js)

Here you have a property that is specifying what files to run. Default content is this:

`specs: [
        `${__dirname}/test/specs/**/*.js`
    ],`

You can edit this content to specify the file you need, or have several custom files, for your different suites. In this example I already mention how to run different configurations.
